import { Question, Subject } from './types';

// ─── Все предметы ЕНТ ────────────────────────────────────────────────────────
export const ALL_SUBJECTS: Subject[] = [
  { id: 'math',        label: 'Математика',                  icon: '📐', color: 'blue',    required: true },
  { id: 'math_lit',    label: 'Мат. грамотность',            icon: '🔢', color: 'indigo',  required: true },
  { id: 'reading',     label: 'Грамотность чтения',          icon: '📖', color: 'violet',  required: true },
  { id: 'history_kz',  label: 'История Казахстана',          icon: '🏛️', color: 'amber',   required: true },
  { id: 'physics',     label: 'Физика',                      icon: '⚡', color: 'yellow',  required: false },
  { id: 'chemistry',   label: 'Химия',                       icon: '🧪', color: 'green',   required: false },
  { id: 'biology',     label: 'Биология',                    icon: '🌿', color: 'emerald', required: false },
  { id: 'geography',   label: 'География',                   icon: '🌍', color: 'teal',    required: false },
  { id: 'informatics', label: 'Информатика',                 icon: '💻', color: 'cyan',    required: false },
  { id: 'english',     label: 'Английский язык',             icon: '🇬🇧', color: 'rose',  required: false },
  { id: 'russian',     label: 'Русский язык',                icon: '🗣️', color: 'pink',    required: false },
  { id: 'world_history', label: 'Всемирная история',         icon: '🌐', color: 'orange',  required: false },
];

// ─── Банк вопросов ────────────────────────────────────────────────────────────
export const QUESTIONS_BANK: Record<string, Question[]> = {
  math: [
    { id: 'm1', subject: 'math', topic: 'Логарифмы',
      text: 'Вычислите: log₂ 16 + log₃ 27',
      options: ['5', '7', '8', '12'], correctAnswer: '7', difficulty: 'easy',
      explanation: 'log₂ 16 = 4 (2⁴=16), log₃ 27 = 3 (3³=27). Итого: 4+3=7.' },
    { id: 'm2', subject: 'math', topic: 'Тригонометрия',
      text: 'Чему равно sin(π/6)?',
      options: ['0', '1/2', '√2/2', '√3/2'], correctAnswer: '1/2', difficulty: 'easy',
      explanation: 'sin(30°) = 1/2 — стандартное табличное значение.' },
    { id: 'm3', subject: 'math', topic: 'Производная',
      text: 'Найдите f\'(x), если f(x) = x³ − 3x² + 5',
      options: ['3x² − 6x', 'x² − 3x', '3x² − 6', '3x³ − 6x'], correctAnswer: '3x² − 6x', difficulty: 'medium',
      explanation: '(x³)\'=3x², (3x²)\'=6x, (5)\'=0. Итого: 3x²−6x.' },
    { id: 'm4', subject: 'math', topic: 'Уравнения',
      text: 'Решите: x² − 5x + 6 = 0',
      options: ['x=1, x=6', 'x=2, x=3', 'x=−2, x=3', 'x=−3, x=−2'], correctAnswer: 'x=2, x=3', difficulty: 'easy',
      explanation: 'По теореме Виета: сумма=5, произведение=6 → x=2, x=3.' },
    { id: 'm5', subject: 'math', topic: 'Геометрия',
      text: 'Площадь круга с радиусом 5 см (π≈3.14)?',
      options: ['31.4 см²', '78.5 см²', '15.7 см²', '25 см²'], correctAnswer: '78.5 см²', difficulty: 'easy',
      explanation: 'S = πr² = 3.14 × 25 = 78.5 см².' },
    { id: 'm6', subject: 'math', topic: 'Прогрессии',
      text: 'Сумма 10 членов арифм. прогрессии, где a₁=2, d=3?',
      options: ['155', '120', '185', '140'], correctAnswer: '155', difficulty: 'medium',
      explanation: 'S₁₀ = 10/2 × (2×2 + 9×3) = 5 × 31 = 155.' },
    { id: 'm7', subject: 'math', topic: 'Вероятность',
      text: 'В урне 5 красных и 3 синих шара. Вероятность вытащить красный?',
      options: ['3/8', '5/8', '5/3', '1/2'], correctAnswer: '5/8', difficulty: 'easy',
      explanation: 'P = 5/(5+3) = 5/8.' },
    { id: 'm8', subject: 'math', topic: 'Векторы',
      text: 'Длина вектора ā=(3; 4)?',
      options: ['7', '5', '12', '25'], correctAnswer: '5', difficulty: 'easy',
      explanation: '|ā| = √(9+16) = √25 = 5.' },
  ],

  math_lit: [
    { id: 'ml1', subject: 'math_lit', topic: 'Проценты',
      text: 'Товар стоит 12 000 тг. Скидка 25%. Итоговая цена?',
      options: ['9 000 тг', '10 000 тг', '8 500 тг', '3 000 тг'], correctAnswer: '9 000 тг', difficulty: 'easy',
      explanation: '12000 × 0.75 = 9000 тг.' },
    { id: 'ml2', subject: 'math_lit', topic: 'Статистика',
      text: 'Данные: 5, 7, 3, 9, 1. Среднее арифметическое?',
      options: ['4', '5', '6', '7'], correctAnswer: '5', difficulty: 'easy',
      explanation: '(5+7+3+9+1)/5 = 25/5 = 5.' },
    { id: 'ml3', subject: 'math_lit', topic: 'Диаграммы',
      text: 'Из 200 учеников 40% выбрали физику. Сколько?',
      options: ['40', '60', '80', '100'], correctAnswer: '80', difficulty: 'easy',
      explanation: '200 × 0.40 = 80.' },
    { id: 'ml4', subject: 'math_lit', topic: 'Задачи',
      text: 'Поезд прошёл 360 км за 4 часа. Средняя скорость?',
      options: ['80 км/ч', '90 км/ч', '100 км/ч', '120 км/ч'], correctAnswer: '90 км/ч', difficulty: 'easy',
      explanation: 'v = 360/4 = 90 км/ч.' },
    { id: 'ml5', subject: 'math_lit', topic: 'Множества',
      text: 'A={1,2,3,4}, B={3,4,5,6}. Мощность A∩B?',
      options: ['2', '4', '6', '8'], correctAnswer: '2', difficulty: 'medium',
      explanation: 'A∩B = {3,4}. Мощность = 2.' },
  ],

  physics: [
    { id: 'ph1', subject: 'physics', topic: 'Кинематика',
      text: 'Тело: v₀=10 м/с, a=2 м/с². Скорость через 5 с?',
      options: ['15 м/с', '20 м/с', '25 м/с', '30 м/с'], correctAnswer: '20 м/с', difficulty: 'easy',
      explanation: 'v = v₀ + at = 10 + 2×5 = 20 м/с.' },
    { id: 'ph2', subject: 'physics', topic: 'Динамика',
      text: 'Сила 20 Н, масса 4 кг. Ускорение?',
      options: ['2 м/с²', '4 м/с²', '5 м/с²', '80 м/с²'], correctAnswer: '5 м/с²', difficulty: 'easy',
      explanation: 'a = F/m = 20/4 = 5 м/с².' },
    { id: 'ph3', subject: 'physics', topic: 'Электричество',
      text: 'R=10 Ом, I=2 А. Напряжение?',
      options: ['5 В', '8 В', '12 В', '20 В'], correctAnswer: '20 В', difficulty: 'easy',
      explanation: 'U = IR = 2×10 = 20 В.' },
    { id: 'ph4', subject: 'physics', topic: 'Термодинамика',
      text: 'При изотермическом процессе V увеличился в 2 раза. Что с давлением?',
      options: ['Увеличилось в 2 раза', 'Уменьшилось в 2 раза', 'Не изменилось', 'Уменьшилось в 4 раза'],
      correctAnswer: 'Уменьшилось в 2 раза', difficulty: 'medium',
      explanation: 'Закон Бойля-Мариотта: pV=const. V×2 → p/2.' },
    { id: 'ph5', subject: 'physics', topic: 'Оптика',
      text: 'Скорость света в вакууме:',
      options: ['3×10⁶ м/с', '3×10⁸ м/с', '3×10¹⁰ м/с', '3×10⁵ км/с'], correctAnswer: '3×10⁸ м/с', difficulty: 'easy',
      explanation: 'c ≈ 3×10⁸ м/с — фундаментальная константа.' },
  ],

  chemistry: [
    { id: 'ch1', subject: 'chemistry', topic: 'Строение атома',
      text: 'Сколько протонов у кислорода (O, номер 8)?',
      options: ['6', '7', '8', '16'], correctAnswer: '8', difficulty: 'easy',
      explanation: 'Порядковый номер = число протонов = 8.' },
    { id: 'ch2', subject: 'chemistry', topic: 'Реакции',
      text: 'При горении CH₄ образуется:',
      options: ['CO + H₂O', 'CO₂ + H₂O', 'C + H₂', 'CH₃OH'], correctAnswer: 'CO₂ + H₂O', difficulty: 'easy',
      explanation: 'CH₄ + 2O₂ → CO₂ + 2H₂O.' },
    { id: 'ch3', subject: 'chemistry', topic: 'Органика',
      text: 'Какой класс веществ имеет формулу CₙH₂ₙ?',
      options: ['Алканы', 'Алкены', 'Алкины', 'Арены'], correctAnswer: 'Алкены', difficulty: 'medium',
      explanation: 'CₙH₂ₙ — общая формула алкенов (одна двойная связь C=C).' },
    { id: 'ch4', subject: 'chemistry', topic: 'Электролиз',
      text: 'Что происходит на катоде при электролизе?',
      options: ['Окисление', 'Восстановление', 'Нейтрализация', 'Гидролиз'], correctAnswer: 'Восстановление', difficulty: 'medium',
      explanation: 'Катод (−) — восстановление (приём электронов).' },
    { id: 'ch5', subject: 'chemistry', topic: 'Молярная масса',
      text: 'Молярная масса H₂O?',
      options: ['8 г/моль', '17 г/моль', '18 г/моль', '20 г/моль'], correctAnswer: '18 г/моль', difficulty: 'easy',
      explanation: 'M(H₂O) = 2×1 + 16 = 18 г/моль.' },
  ],

  biology: [
    { id: 'bi1', subject: 'biology', topic: 'Клетка',
      text: 'Где синтезируются белки в клетке?',
      options: ['Ядро', 'Митохондрия', 'Рибосома', 'Лизосома'], correctAnswer: 'Рибосома', difficulty: 'easy',
      explanation: 'Рибосомы — органоиды синтеза белка.' },
    { id: 'bi2', subject: 'biology', topic: 'Генетика',
      text: 'Сколько хромосом в соматической клетке человека?',
      options: ['23', '46', '48', '92'], correctAnswer: '46', difficulty: 'easy',
      explanation: '46 хромосом (23 пары) в диплоидных клетках.' },
    { id: 'bi3', subject: 'biology', topic: 'Фотосинтез',
      text: 'В каком органоиде происходит фотосинтез?',
      options: ['Митохондрия', 'Хлоропласт', 'Вакуоль', 'Ядро'], correctAnswer: 'Хлоропласт', difficulty: 'easy',
      explanation: 'Хлоропласты содержат хлорофилл для фотосинтеза.' },
    { id: 'bi4', subject: 'biology', topic: 'Эволюция',
      text: 'Кто разработал теорию естественного отбора?',
      options: ['Ламарк', 'Мендель', 'Дарвин', 'Вавилов'], correctAnswer: 'Дарвин', difficulty: 'easy',
      explanation: 'Чарлз Дарвин — автор теории эволюции путём естественного отбора.' },
    { id: 'bi5', subject: 'biology', topic: 'ДНК',
      text: 'Нуклеотиды ДНК:',
      options: ['A, U, G, C', 'A, T, G, C', 'A, T, U, C', 'A, G, T, U'], correctAnswer: 'A, T, G, C', difficulty: 'medium',
      explanation: 'ДНК: Аденин, Тимин, Гуанин, Цитозин. В РНК — Урацил вместо Тимина.' },
  ],

  geography: [
    { id: 'ge1', subject: 'geography', topic: 'Казахстан',
      text: 'Какое место по площади занимает Казахстан в мире?',
      options: ['7-е', '8-е', '9-е', '10-е'], correctAnswer: '9-е', difficulty: 'easy',
      explanation: 'Казахстан — 9-я по площади страна (2 724 902 км²).' },
    { id: 'ge2', subject: 'geography', topic: 'Горы',
      text: 'Самая высокая горная система Казахстана?',
      options: ['Алтай', 'Тянь-Шань', 'Каратау', 'Мугоджары'], correctAnswer: 'Тянь-Шань', difficulty: 'medium',
      explanation: 'Тянь-Шань — высочайшая система. Пик Хан-Тенгри — 6995 м.' },
    { id: 'ge3', subject: 'geography', topic: 'Климат',
      text: 'Какой климат характерен для большей части Казахстана?',
      options: ['Субтропический', 'Резко континентальный', 'Морской', 'Арктический'],
      correctAnswer: 'Резко континентальный', difficulty: 'easy',
      explanation: 'Большая удалённость от океанов — резко континентальный климат.' },
    { id: 'ge4', subject: 'geography', topic: 'Реки',
      text: 'Самая длинная река Казахстана?',
      options: ['Иртыш', 'Сырдарья', 'Или', 'Урал'], correctAnswer: 'Иртыш', difficulty: 'medium',
      explanation: 'Иртыш — самая длинная река в Казахстане (≈4248 км).' },
    { id: 'ge5', subject: 'geography', topic: 'Столица',
      text: 'Как называется столица Казахстана с 2022 года?',
      options: ['Алматы', 'Астана', 'Нур-Султан', 'Акмола'], correctAnswer: 'Астана', difficulty: 'easy',
      explanation: 'В 2022 году городу возвращено название Астана.' },
  ],

  history_kz: [
    { id: 'hk1', subject: 'history_kz', topic: 'Казахское ханство',
      text: 'Год образования Казахского ханства?',
      options: ['1455', '1465', '1480', '1500'], correctAnswer: '1465', difficulty: 'easy',
      explanation: 'Казахское ханство основано около 1465 г. ханами Кереем и Жанибеком.' },
    { id: 'hk2', subject: 'history_kz', topic: 'Независимость',
      text: 'Год провозглашения независимости Казахстана?',
      options: ['1989', '1990', '1991', '1992'], correctAnswer: '1991', difficulty: 'easy',
      explanation: 'Казахстан провозгласил независимость 16 декабря 1991 года.' },
    { id: 'hk3', subject: 'history_kz', topic: 'Джунгарские войны',
      text: 'Как называется период 1723–1727 гг.?',
      options: ['Ақтабан шұбырынды', 'Ұлы жеңіс', 'Орда жорығы', 'Анракай'],
      correctAnswer: 'Ақтабан шұбырынды', difficulty: 'medium',
      explanation: '"Ақтабан шұбырынды" — Великое бедствие, массовое отступление казахов.' },
    { id: 'hk4', subject: 'history_kz', topic: 'Советский период',
      text: 'Когда Казахская АССР стала Казахской ССР?',
      options: ['1920', '1925', '1936', '1945'], correctAnswer: '1936', difficulty: 'medium',
      explanation: 'В 1936 году — преобразование в союзную республику.' },
    { id: 'hk5', subject: 'history_kz', topic: 'Культура',
      text: 'Кто является автором «Қозы Көрпеш — Баян Сұлу»?',
      options: ['Абай', 'Жамбыл', 'Народное творчество', 'Дулат'],
      correctAnswer: 'Народное творчество', difficulty: 'medium',
      explanation: 'Это казахский народный эпос — произведение устного творчества.' },
  ],

  world_history: [
    { id: 'wh1', subject: 'world_history', topic: 'Рим',
      text: 'В каком году пала Западная Римская империя?',
      options: ['395', '410', '476', '527'], correctAnswer: '476', difficulty: 'medium',
      explanation: '476 н.э. — свержение Ромула Августула.' },
    { id: 'wh2', subject: 'world_history', topic: 'Средневековье',
      text: 'Великая Хартия вольностей подписана в:',
      options: ['1066', '1215', '1415', '1492'], correctAnswer: '1215', difficulty: 'medium',
      explanation: 'Magna Carta — 1215 год, король Иоанн Безземельный.' },
    { id: 'wh3', subject: 'world_history', topic: 'Революции',
      text: 'Великая французская революция началась в:',
      options: ['1776', '1789', '1799', '1804'], correctAnswer: '1789', difficulty: 'easy',
      explanation: '1789 год — взятие Бастилии 14 июля.' },
    { id: 'wh4', subject: 'world_history', topic: 'XX век',
      text: 'Год окончания Второй мировой войны?',
      options: ['1943', '1944', '1945', '1946'], correctAnswer: '1945', difficulty: 'easy',
      explanation: '1945 год: Европа — май, Тихий океан — сентябрь.' },
    { id: 'wh5', subject: 'world_history', topic: 'Открытия',
      text: 'В каком году Колумб достиг Америки?',
      options: ['1488', '1492', '1498', '1519'], correctAnswer: '1492', difficulty: 'easy',
      explanation: '12 октября 1492 года Колумб достиг берегов Америки.' },
  ],

  english: [
    { id: 'en1', subject: 'english', topic: 'Present Perfect',
      text: '"She ___ (work) here since 2020."',
      options: ['works', 'worked', 'has worked', 'is working'], correctAnswer: 'has worked', difficulty: 'medium',
      explanation: '"Since" требует Present Perfect: "She has worked here since 2020."' },
    { id: 'en2', subject: 'english', topic: 'Лексика',
      text: 'Synonym of "happy":',
      options: ['Sad', 'Joyful', 'Angry', 'Tired'], correctAnswer: 'Joyful', difficulty: 'easy',
      explanation: '"Joyful" = full of joy. Синоним "happy".' },
    { id: 'en3', subject: 'english', topic: 'Косвенная речь',
      text: '"She asked me ___ I wanted to go."',
      options: ['that', 'what', 'which', 'how'], correctAnswer: 'what', difficulty: 'medium',
      explanation: 'Indirect question: "She asked me what I wanted."' },
    { id: 'en4', subject: 'english', topic: 'Предлоги',
      text: '"I will meet you ___ Monday ___ 9 a.m."',
      options: ['in/at', 'on/at', 'at/on', 'on/in'], correctAnswer: 'on/at', difficulty: 'easy',
      explanation: '"On" — дни недели, "at" — время. On Monday at 9 a.m.' },
    { id: 'en5', subject: 'english', topic: 'Словообразование',
      text: 'Noun form of "discover"?',
      options: ['discovers', 'discoverable', 'discovery', 'discoverer'], correctAnswer: 'discovery', difficulty: 'easy',
      explanation: '"Discovery" — существительное от "discover".' },
  ],

  russian: [
    { id: 'ru1', subject: 'russian', topic: 'Орфография',
      text: 'Как правильно: «пр_обрести»?',
      options: ['преобрести', 'приобрести', 'пр\'обрести', 'прообрести'],
      correctAnswer: 'приобрести', difficulty: 'medium',
      explanation: 'Приставка ПРИ- — значение присоединения: приобрести.' },
    { id: 'ru2', subject: 'russian', topic: 'Пунктуация',
      text: 'Правильная пунктуация:',
      options: ['Солнце зашло, и стало темнее.', 'Солнце зашло и, стало темнее.',
                 'Солнце, зашло и стало темнее.', 'Солнце зашло и стало, темнее.'],
      correctAnswer: 'Солнце зашло, и стало темнее.', difficulty: 'easy',
      explanation: 'В ССП перед «и» ставится запятая.' },
    { id: 'ru3', subject: 'russian', topic: 'Морфология',
      text: 'Часть речи слова «бегом»?',
      options: ['Существительное', 'Наречие', 'Деепричастие', 'Глагол'],
      correctAnswer: 'Наречие', difficulty: 'medium',
      explanation: '"Бегом" — наречие (как?), неизменяемое слово.' },
    { id: 'ru4', subject: 'russian', topic: 'Лексика',
      text: 'Антоним слова «скупой»:',
      options: ['Жадный', 'Щедрый', 'Богатый', 'Бедный'],
      correctAnswer: 'Щедрый', difficulty: 'easy',
      explanation: 'Антоним «скупой» — «щедрый».' },
    { id: 'ru5', subject: 'russian', topic: 'Синтаксис',
      text: 'Сложноподчинённое предложение:',
      options: ['Пошёл дождь, и мы остались дома.', 'Мы остались дома, потому что пошёл дождь.',
                 'Пошёл дождь; мы остались дома.', 'Мы остались дома: пошёл дождь.'],
      correctAnswer: 'Мы остались дома, потому что пошёл дождь.', difficulty: 'medium',
      explanation: 'СПП — с подчинительным союзом «потому что».' },
  ],

  informatics: [
    { id: 'it1', subject: 'informatics', topic: 'Двоичная система',
      text: '1010₂ в десятичной системе =',
      options: ['8', '10', '12', '14'], correctAnswer: '10', difficulty: 'easy',
      explanation: '1×8 + 0×4 + 1×2 + 0×1 = 10.' },
    { id: 'it2', subject: 'informatics', topic: 'Алгоритмы',
      text: 'Сложность быстрой сортировки в среднем?',
      options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'],
      correctAnswer: 'O(n log n)', difficulty: 'medium',
      explanation: 'Quicksort в среднем — O(n log n).' },
    { id: 'it3', subject: 'informatics', topic: 'SQL',
      text: 'Оператор SQL для выборки данных?',
      options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], correctAnswer: 'SELECT', difficulty: 'easy',
      explanation: 'SELECT — выборка (чтение) данных из таблицы.' },
    { id: 'it4', subject: 'informatics', topic: 'Python',
      text: 'Что выведет: print(2 ** 8)?',
      options: ['16', '64', '256', '512'], correctAnswer: '256', difficulty: 'easy',
      explanation: '** — степень. 2⁸ = 256.' },
    { id: 'it5', subject: 'informatics', topic: 'Сети',
      text: 'IP-адрес — это:',
      options: ['Имя компьютера', 'Уникальный числовой идентификатор устройства', 'Пароль Wi-Fi', 'Название браузера'],
      correctAnswer: 'Уникальный числовой идентификатор устройства', difficulty: 'easy',
      explanation: 'IP-адрес (напр. 192.168.1.1) — идентификатор в сети.' },
  ],
};

// ─── Утилиты ─────────────────────────────────────────────────────────────────
export function getDiagnosticQuestions(subjectIds: string[]): Question[] {
  const result: Question[] = [];
  for (const sid of subjectIds) {
    const qs = QUESTIONS_BANK[sid];
    if (qs) result.push(...qs.slice(0, 2));
  }
  return result;
}

export function getSubjectQuestions(subjectId: string): Question[] {
  return QUESTIONS_BANK[subjectId] || [];
}

export const REQUIRED_SUBJECTS = ALL_SUBJECTS.filter(s => s.required).map(s => s.id);
